/* MTI_DPI */

/*
 * Copyright 2002-2016 Mentor Graphics Corporation.
 *
 * Note:
 *   This file is automatically generated.
 *   Please do not edit this file - you will lose your edits.
 *
 * Settings when this file was generated:
 *   PLATFORM = 'win32pe'
 */
#ifndef INCLUDED_IMAGE
#define INCLUDED_IMAGE

#ifdef __cplusplus
#define DPI_LINK_DECL  extern "C" 
#else
#define DPI_LINK_DECL 
#endif

#include "svdpi.h"



DPI_LINK_DECL DPI_DLLESPEC
svLogic
create_image(
    int width,
    int height);

DPI_LINK_DECL DPI_DLLESPEC
int
free_image();

DPI_LINK_DECL DPI_DLLESPEC
int
load_pix(
    int pix_pos,
    unsigned int* R,
    unsigned int* G,
    unsigned int* B);

DPI_LINK_DECL DPI_DLLESPEC
int
open_image(
    const char* path,
    int width,
    int height);

DPI_LINK_DECL DPI_DLLESPEC
svLogic
save_image(
    const char* path,
    int width,
    int height);

DPI_LINK_DECL DPI_DLLESPEC
svLogic
store_pix(
    int pix_pos,
    int R,
    int G,
    int B);

#endif 
